apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-deployment
  namespace: kubernetes
  labels:
    app: kub-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kub-deployment
  template:
    metadata:
      labels:
        app: kub-deployment
    spec:
      containers:
        - name: kub-deployment
          image: cribb/kubernetes-exercise:0.0.1
          imagePullPolicy: IfNotPresent