apiVersion: v1
kind: Service
metadata:
  name: kub-service
  namespace: kubernetes
spec:
  selector:
    app: kub-deployment
  ports:
    - name: application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP